"""empty message

Revision ID: 5f0f144fe3e7
Revises: 9b2363f9b510
Create Date: 2024-03-10 03:04:28.670422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0f144fe3e7'
down_revision = '9b2363f9b510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('billing_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('prescribed_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('cost_of_services')
        batch_op.drop_column('cost_of_tests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_of_tests', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cost_of_services', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.alter_column('prescribed_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('due_date')
        batch_op.drop_column('billing_date')
        batch_op.drop_column('status')

    op.drop_table('billing_items')
    # ### end Alembic commands ###
