"""modified appointments table

Revision ID: 66ed127ae832
Revises: f94e1a61cd6e
Create Date: 2024-03-06 10:14:30.386720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66ed127ae832'
down_revision = 'f94e1a61cd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=False))
        batch_op.drop_constraint('appointments_service_id_fkey', type_='foreignkey')
        batch_op.drop_column('appointment_datetime')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('appointment_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('appointments_service_id_fkey', 'services', ['service_id'], ['id'])
        batch_op.drop_column('start_time')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
